---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: flux-secrets
  namespace: default
  labels:
    app: flux
    release: flux-capd
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames: ["flux-capd-git-deploy"]
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux-secrets
  namespace: default
  labels:
    app: flux
    release: flux-capd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-secrets
subjects:
  - name: default
    namespace: default
    kind: ServiceAccount
